### ISSUE TITLE
DeskTube | To-Do List

### ISSUE THREAD

**Issue by malisipi** [malisipi/DeskTube#1]
# API
- [ ] Support custom API
- [ ] Optimize for low internet usage

# Communication
- [x] Support broadcast channel

# Pages/Views
- [x] Trending
- [x] Search
- [ ] Player
  - [ ] Some buttons is not working
- [ ] Next Videos
- [ ] Channel Page

# Components
- [x] Window
  - [ ] Z-Index Support
- [x] Taskbar
  - [ ] Windows Support
- [x] Video Preview
  - [ ] Compact View
  - [ ] Default View

# Mobile
- [ ] Disable popup mode since it's unsupported in mobile. 
- [ ] Resize thumb is really tiny. Make a way to make it's bigger
- [ ] Player is really unusable

*Completed Sub-Tasks (except it's really important feature) will be deleted from here*

## If you're have a feature request or bug report, please comment here or create a new issue
